name: Build omnivoice.cpp

on:
  workflow_dispatch:

env:
  CUDA_VERSION: "12.6.3"

jobs:
  build-allvariants-cuda:
    name: "omnivoice.cpp build"
    runs-on: windows-2022

    steps:
      - name: Checkout omnivoice.cpp
        uses: actions/checkout@v4
        with:
          repository: ServeurpersoCom/omnivoice.cpp
          ref: master
          submodules: recursive

      - name: Install CUDA Toolkit ${{ env.CUDA_VERSION }}
        uses: Jimver/cuda-toolkit@master
        id: cuda-toolkit
        with:
          cuda: ${{ env.CUDA_VERSION }}
          method: network
          sub-packages: '["nvcc", "cudart", "cublas", "cublas_dev", "thrust"]'

      - name: Fix CUDA VS Integration
        shell: cmd
        run: |
          xcopy /s /y "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\extras\visual_studio_integration\MSBuildExtensions\*" "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\BuildCustomizations\"

      - name: Build
        continue-on-error: true
        run: ./buildall.cmd

      - name: Upload artefact
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: omnivoice-cpp
          path: build
          retention-days: 30
