name: Build omnivoice.cpp

on:
  workflow_dispatch:

env:
  CUDA_VERSION: "12.6.3"
  CUDA_ARCH:        "75"  

jobs:
  build-allvariants-cuda:
    name: "omnivoice.cpp build"
    runs-on: windows-2022

    steps:
      - name: Checkout omnivoice.cpp
        uses: actions/checkout@v4
        with:
          repository: ServeurpersoCom/omnivoice.cpp
          ref: master
          submodules: recursive

      - name: Install CUDA Toolkit ${{ env.CUDA_VERSION }}
        uses: Jimver/cuda-toolkit@master
        id: cuda-toolkit
        with:
          cuda: ${{ env.CUDA_VERSION }}
          method: network
          sub-packages: '["nvcc", "cudart", "cublas", "cublas_dev", "thrust", "visual_studio_integration"]'

      - name: Fix CUDA VS Integration
        shell: cmd
        run: |
          xcopy /s /y "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\extras\visual_studio_integration\MSBuildExtensions\*" "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\BuildCustomizations\"          

      - name: Build
        continue-on-error: true
        run: |
          mkdir build
          cd build
          cmake .. `
            -DGGML_CUDA=ON `
            -DGGML_CUDA_CUB_3DOT2=ON `
            -DGGML_SSE42=ON `
            -DGGML_AVX=ON `
            -DGGML_F16C=ON `
            -DGGML_FMA=ON `
            -DGGML_AVX2=ON `
            -DGGML_BMI2=ON `
            -DGGML_AVX512=ON `
            -DGGML_AVX512_VBMI=ON `
            -DGGML_AVX512_VNNI=ON `
            -DGGML_NATIVE=OFF `
            -DGGML_SCHED_MAX_COPIES=1 `
            -DCMAKE_CUDA_ARCHITECTURES="${{ env.CUDA_ARCH }}" `
            -DGGML_LTO=ON
          
          cmake --build . --config Release -j 2

      - name: Upload artefact
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: omnivoice-cpp
          path: build/Release
          retention-days: 30
